In [37]:
import mmcv

In [38]:
class_split = mmcv.load('appendix/mured/class_split.pkl')  

In [39]:
class_freq = mmcv.load('appendix/mured/class_freq.pkl')
class_freq

{'gt_labels': [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 

In [40]:
new_condition_prob = class_freq['condition_prob'][:, class_split['mid']]
new_condition_prob = new_condition_prob[class_split['mid'],:]
new_condition_prob

class_freq['condition_prob'] = new_condition_prob

In [41]:
import numpy as np
new_gt_labels = np.array(class_freq['gt_labels'])[:, class_split['mid']]
class_freq['gt_labels'] = new_gt_labels
class_freq['gt_labels']

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [42]:
class_freq['neg_class_freq'] = class_freq['neg_class_freq'][class_split['mid']]
class_freq['neg_class_freq']

array([1629, 1634, 1638, 1639, 1693, 1701])

In [43]:
class_freq['class_freq'] = class_freq['class_freq'][class_split['mid']]
class_freq['class_freq']

array([135, 130, 126, 125,  71,  63])

In [44]:
class_freq['gt_labels']

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [45]:
mmcv.dump(class_freq, 'appendix/mured/group2/class_freq_new.pkl')

In [46]:
class_split['mid']

[2, 6, 5, 4, 7, 8]

In [49]:
mmcv.load('appendix/mured/group2_all_zero/class_split.pkl')

{'head': [6], 'mid': [0, 1, 2, 3, 4, 5], 'tail': [0, 1, 2, 3, 4, 5]}