In [2]:
import re
import mmcv
from sklearn.metrics import average_precision_score
import numpy as np
from typing import Tuple

def get_epoch(file_path: str):
# Read the file
  with open(file_path, "r") as file:
      content = file.read()

  # Use regex to extract the number after "mAP:"
  match = re.search(r"mAP:\s*(\d+)", content)
  if match:
      epoch = int(match.group(1))
      return epoch
  else:
      print("Epoch not found.")

def get_gt_pred(file_path: str):
    output_and_gt = mmcv.load(file_path)
    return np.array(output_and_gt[0]['outputs']), np.array(output_and_gt[0]['gt_labels'])
# import numpy as np
# outputs_result = None
# gt_labels_result = None
# for i in range(1,5):
#     file_path = f"coco/coco_uniform_bce_group{i}.txt"
#     epoch = get_epoch(file_path)
#     outputs, gt_labels = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_group{i}/gt_and_results_e{epoch}.pkl")
#     if outputs_result is None:
#         outputs_result = outputs
#     else:
#         outputs_result = np.hstack((np.array(outputs_result), np.array(outputs)))
#     if gt_labels_result is None:
#         gt_labels_result = gt_labels
#     else:
#         gt_labels_result = np.hstack((np.array(gt_labels_result), np.array(gt_labels)))
    

def calculate_mAP(all_preds: np.ndarray, all_labels: np.ndarray) -> Tuple[np.float64, list]:
    label_cnt = len(all_labels[0])
    mAP = 0
    mAP_per_label = []
    # print(label_cnt)
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    for i in range(label_cnt):
        # print(np.sum(all_labels[:, i]) > 0)
        AP = average_precision_score(all_labels[:, i], all_preds[:, i])
        mAP_per_label.append(AP)
        mAP += AP

    mAP /= label_cnt
    APs = average_precision_score(all_labels, all_preds, average=None) 
    mAP = APs.mean()

    return mAP, mAP_per_label
def get_3_split_map(outputs_result, gt_labels_result):
    map_score1 =  calculate_mAP( np.array(outputs_result)[:, :22], np.array(gt_labels_result)[:, :22])
    # print(f"head mAP: {map_score1[0]:.4f}")
    # print(np.array(map_score[1]))
    map_score2 =  calculate_mAP( np.array(outputs_result)[:, 22:55], np.array(gt_labels_result)[:, 22:55])
    # print(f"mid mAP: {map_score2[0]:.4f}")
    # print(np.array(map_score[1]))
    map_score3 =  calculate_mAP( np.array(outputs_result)[:, 55:], np.array(gt_labels_result)[:, 55:])

    total = calculate_mAP( np.array(outputs_result), np.array(gt_labels_result))
    # print(f"tail mAP: {map_score3[0]:.4f}")
    print([round(map_score1[0], 4), round(map_score2[0], 4), round(map_score3[0], 4), round(total[0], 4)])
    # print(np.array(map_score[1]))


# get_3_split_map(outputs_result, gt_labels_result)

/home/mark/Desktop/工研院/DistributionBalancedLoss/.venv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/mark/Desktop/工研院/DistributionBalancedLoss/.venv/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(


In [15]:
import ast
import pandas as pd
original_position = pd.read_csv("/home/mark/Desktop/工研院/multi-label_classification/data/coco/group2_original_positions_per_step.csv")
original_position['original_positions'] = original_position['original_positions'].apply(ast.literal_eval)
def get_original_index(step):
    if step in original_position['step'].values:
        return original_position.loc[original_position['step'] == step, 'original_positions'].values[0]
    else:
        raise ValueError(f"Step {step} not found.")

In [18]:
from tqdm import tqdm
best_score_list = []
range_left, range_right = 11, 50
for ri in tqdm(range(4, 11)):
    work_dir_str = f"LT_coco_resnet50_pfc_DB_uniform_bce_35_6_CVIR_group2_step{ri}"
    best_score = 0
    best_epoch = 0
    epoch_list = []
    for i in range(1,81):
        # epoch = get_epoch(file_path)
        outputs, gt_labels = get_gt_pred(f"work_dirs/{work_dir_str}/gt_and_results_e{i}.pkl")
        epoch_list.append((outputs, gt_labels))
        map_score = calculate_mAP(outputs[:, get_original_index(ri)], gt_labels[:,get_original_index(ri) ])
        if map_score[0] > best_score:
            best_score = map_score[0]
            best_epoch = i
    best_score_list.append((best_score, best_epoch))



100%|██████████| 7/7 [00:36<00:00,  5.19s/it]


In [19]:
best_score_list

[(0.6047756157989091, 37),
 (0.6038071354207358, 42),
 (0.6017351995485056, 53),
 (0.5995358795664304, 50),
 (0.5999955079244591, 53),
 (0.6008709706791012, 78),
 (0.6008362300256025, 56)]

In [18]:
best_score_list

[0.6229675280352791]

In [24]:
best_epoch

28

In [112]:
outputs[:,get_original_index(10)].shape

(5000, 39)

In [111]:
best_score_list

[(0.6047600344875798, 36),
 (0.6058464672269758, 32),
 (0.6017389176220953, 38),
 (0.6045177137242295, 36),
 (0.6045391143791078, 50),
 (0.6047300344764673, 42),
 (0.6023692674625177, 48),
 (0.6033794152990145, 53),
 (0.6009239422498157, 52),
 (0.6019962043015692, 63)]

In [57]:
best_score_list

[(0.6244537242756895, 9),
 (0.631269683207284, 10),
 (0.6272452772954641, 15),
 (0.6298287881205433, 13),
 (0.6319336448824721, 16),
 (0.6304857578304011, 15),
 (0.6267199275707046, 17),
 (0.6254485757250204, 19),
 (0.6228322864000027, 20),
 (0.6241215528569193, 21),
 (0.6213801213078801, 29),
 (0.6235290169708279, 22),
 (0.6232340825305664, 28),
 (0.6228016584622147, 26),
 (0.6218446863189525, 35),
 (0.6229577895391062, 32),
 (0.6228398396331677, 30)]

In [27]:
last = outputs[:,range_left: 11 ] 

In [28]:
(outputs[:, -30:] == last).every()

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [21]:
best_score_list

[(0.6302228720370208, 68),
 (0.6288683594595657, 71),
 (0.6227333914497694, 58),
 (0.6216182740062414, 64),
 (0.6267958467001103, 74),
 (0.6269370829145641, 72),
 (0.6111917834746652, 77),
 (0.6110707802614683, 78),
 (0.6156081032266659, 68),
 (0.5972553884034454, 75),
 (0.586243483137789, 73),
 (0.5809931827375383, 77)]

In [10]:
best_score_list

[(0.6244537242756895, 9),
 (0.631269683207284, 10),
 (0.6272452772954641, 15),
 (0.6298287881205433, 13),
 (0.6319336448824721, 16),
 (0.6304857578304011, 15),
 (0.6267199275707046, 17),
 (0.6254485757250204, 19),
 (0.6228322864000027, 20),
 (0.6241215528569193, 21),
 (0.6213801213078801, 29),
 (0.6235290169708279, 22),
 (0.6232340825305664, 28),
 (0.6228016584622147, 26),
 (0.6218446863189525, 35),
 (0.6229577895391062, 32),
 (0.6228398396331677, 30)]

## best group1 index 5 (0.6319336448824721, 16)

In [83]:
selected_indexes = [
    28,  # suitcase
    34,  # baseball glove
    78,  # teddy bear
    7,   # boat
    38,  # tennis racket
    14,  # bird
    6,   # train
    17,  # horse
    35,  # skateboard
    54,  # donut
    76,  # scissors
    51,  # hot dog
    12,  # stop sign
    30,  # skis
    10,  # fire hydrant
    29,  # frisbee
    79,  # toothbrush
    19,  # cow
    33,  # kite
    36,  # surfboard
    4,   # airplane
    67,  # toaster
    13,  # parking meter
    20,  # elephant
    31,  # snowboard
    18,  # sheep
    22,  # zebra
    23,  # giraffe
    21,  # bear
    77   # hair drier
]

# selected_indexes = [
#     0,   # person
#     57,  # dining table
#     56,  # chair
#     41,  # cup
#     39,  # bottle
#     44,  # bowl
#     70,  # book
#     2,   # car
#     68,  # sink
#     43,  # knife
#     60   # tv
# ]


In [13]:
best_epoch = 0
best_score = 0

def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def calculate_mAP(all_preds: np.ndarray, all_labels: np.ndarray) -> Tuple[np.float64, list]:
    all_preds = sigmoid(all_preds)
    label_cnt = len(all_labels[0])
    mAP = 0
    mAP_per_label = []
    # print(label_cnt)
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    for i in range(label_cnt):
        # print(np.sum(all_labels[:, i]) > 0)
        AP = average_precision_score(all_labels[:, i], all_preds[:, i])
        mAP_per_label.append(AP)
        mAP += AP

    mAP /= label_cnt
    APs = average_precision_score(all_labels, all_preds, average=None) 
    mAP = APs.mean()

    return mAP, mAP_per_label
for i in range(16,17):
    # epoch = get_epoch(file_path)
    # outputs, gt_labels = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group1_l0_r5/gt_and_results_e{i}.pkl")
    outputs, gt_labels = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_classaware_bce/gt_and_results_e6.pkl")
    # epoch_list.append((outputs, gt_labels))
    map_score = calculate_mAP(outputs[:, :], gt_labels[:, :])
    if map_score[0] > best_score:
        best_score = map_score[0]
        best_epoch = i

print(best_score, best_epoch)

0.5967825588474797 16


In [16]:
outputs.min()

-9.805365

In [85]:
outputs[:,selected_indexes].shape

(5000, 30)

## score of group3 in bce all  0.5754014458097789 80

In [35]:
outputs[:,selected_indexes].shape

(5000, 30)

In [78]:
class_split = mmcv.load("appendix/coco/longtail2017/class_split.pkl")

outputs, gt_labels = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_classaware_DBloss/gt_and_results_e8.pkl")

head_score = calculate_mAP(outputs[:, list(class_split["head"])], gt_labels[:, list(class_split["head"])])[0]
mid_score = calculate_mAP(outputs[:, list(class_split["middle"])], gt_labels[:, list(class_split["middle"])])[0]
tail_score = calculate_mAP(outputs[:, list(class_split["tail"])], gt_labels[:, list(class_split["tail"])])[0]


# head_score = calculate_mAP(outputs[:, :22], gt_labels[:, :22])[0]
# mid_score = calculate_mAP(outputs[:, 22:55], gt_labels[:, 22:55])[0]
# tail_score = calculate_mAP(outputs[:, 55:], gt_labels[:, 55:])[0]
total_score = calculate_mAP(outputs, gt_labels)[0]

print(f"head mAP: {head_score:.4f}")
print(f"mid mAP: {mid_score:.4f}")
print(f"tail mAP: {tail_score:.4f}")
print(f"total mAP: {total_score:.4f}")


head mAP: 0.5328
mid mAP: 0.6091
tail mAP: 0.5618
total mAP: 0.5733


In [79]:
gt_labels.sum(axis=0)

array([2693,  149,  535,  159,   97,  189,  157,  250,  121,  191,   86,
         69,   37,  235,  125,  184,  177,  128,   65,   87,   89,   49,
         85,  101,  228,  174,  292,  145,  105,   84,  120,   49,  169,
         91,   97,  100,  127,  149,  167,  379,  110,  390,  155,  181,
        153,  314,  103,   76,   98,   85,   71,   81,   51,  153,   62,
        124,  580,  195,  172,  149,  501,  149,  207,  183,   88,  145,
        106,  214,   54,  115,    8,  187,  101,  230,  204,  137,   28,
         94,    9,   34])

In [81]:
import pandas as pd
df = pd.read_csv("/home/mark/Desktop/工研院/multi-label_classification/data/coco/test_data.csv", index_col=0)
np.array(df.sum(axis=0))

array([2693,  149,  535,  159,   97,  189,  157,  250,  121,  191,   86,
         69,   37,  235,  125,  184,  177,  128,   65,   87,   89,   49,
         85,  101,  228,  174,  292,  145,  105,   84,  120,   49,  169,
         91,   97,  100,  127,  149,  167,  379,  110,  390,  155,  181,
        153,  314,  103,   76,   98,   85,   71,   81,   51,  153,   62,
        124,  580,  195,  172,  149,  501,  149,  207,  183,   88,  145,
        106,  214,   54,  115,    8,  187,  101,  230,  204,  137,   28,
         94,    9,   34])

In [102]:
df.columns

Index(['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
       'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign',
       'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
       'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella',
       'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard',
       'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
       'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork',
       'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange',
       'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair',
       'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv',
       'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
       'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
       'scissors', 'teddy bear', 'hair drier', 'toothbrush'],
      dtype='object')

In [105]:
# Full COCO class list
coco_classes = "person,bicycle,car,motorcycle,airplane,bus,train,truck,boat,traffic light,fire hydrant,stop sign,parking meter,bench,bird,cat,dog,horse,sheep,cow,elephant,bear,zebra,giraffe,backpack,umbrella,handbag,tie,suitcase,frisbee,skis,snowboard,sports ball,kite,baseball bat,baseball glove,skateboard,surfboard,tennis racket,bottle,wine glass,cup,fork,knife,spoon,bowl,banana,apple,sandwich,orange,broccoli,carrot,hot dog,pizza,donut,cake,chair,couch,potted plant,bed,dining table,toilet,tv,laptop,mouse,remote,keyboard,cell phone,microwave,oven,toaster,sink,refrigerator,book,clock,vase,scissors,teddy bear,hair drier,toothbrush".split(",")

# Target list to find indexes for
target_items = [
    "person", "dining table", "chair", "cup", "bottle",
    "bowl", "book", "car", "sink", "knife", "tv"
]

# Normalize function: lowercase and replace underscores with spaces
def normalize(label):
    return label.strip().lower().replace("_", " ")

# Build normalized list
normalized_coco = [normalize(label) for label in coco_classes]
normalized_targets = [normalize(label) for label in target_items]

# Get indexes
indexes = [normalized_coco.index(label) for label in normalized_targets]

# Output result
print("Target indexes:", indexes)


Target indexes: [0, 60, 56, 41, 39, 45, 73, 2, 71, 43, 62]


In [106]:
np.array(df.columns)[[0, 60, 56, 41, 39, 45, 73, 2, 71, 43, 62]]

array(['person', 'dining table', 'chair', 'cup', 'bottle', 'bowl', 'book',
       'car', 'sink', 'knife', 'tv'], dtype=object)

In [ ]:
"all": [0.5704, 0.636, 0.5447, 0.5894],

In [55]:
calculate_mAP(outputs[:, :11], gt_labels[:, :11])[0]

0.6065970589127846

In [5]:
outputs, gt_labels = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_all/gt_and_results_e{1}.pkl")

In [7]:
gt_labels

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [63]:
gt_labels.sum(axis=0)

array([2693,  149,  535,  159,   97,  189,  157,  250,  121,  191,   86,
         69,   37,  235,  125,  184,  177,  128,   65,   87,   89,   49,
         85,  101,  228,  174,  292,  145,  105,   84,  120,   49,  169,
         91,   97,  100,  127,  149,  167,  379,  110,  390,  155,  181,
        153,  314,  103,   76,   98,   85,   71,   81,   51,  153,   62,
        124,  580,  195,  172,  149,  501,  149,  207,  183,   88,  145,
        106,  214,   54,  115,    8,  187,  101,  230,  204,  137,   28,
         94,    9,   34])

In [74]:
result = mmcv.load("work_dirs/LT_coco_resnet50_pfc_DB/gt_and_results_e10.pkl")
np.array(result[0]['gt_labels']).sum(axis=0)

array([2693,  149,  535,  159,   97,  189,  157,  250,  121,  191,   86,
         69,   37,  235,  125,  184,  177,  128,   65,   87,   89,   49,
         85,  101,  228,  174,  292,  145,  105,   84,  120,   49,  169,
         91,   97,  100,  127,  149,  167,  379,  110,  390,  155,  181,
        153,  314,  103,   76,   98,   85,   71,   81,   51,  153,   62,
        124,  580,  195,  172,  149,  501,  149,  207,  183,   88,  145,
        106,  214,   54,  115,    8,  187,  101,  230,  204,  137,   28,
         94,    9,   34])

In [6]:
# head_score = calculate_mAP(outputs[:, list(class_split["head"])], gt_labels[:, list(class_split["head"])])[0]
# mid_score = calculate_mAP(outputs[:, list(class_split["middle"])], gt_labels[:, list(class_split["middle"])])[0]
# tail_score = calculate_mAP(outputs[:, list(class_split["tail"])], gt_labels[:, list(class_split["tail"])])[0]

outputs1, gt_labels1 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group1_l0_r5/gt_and_results_e16.pkl")
outputs2, gt_labels2 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group2/gt_and_results_e30.pkl")
outputs3, gt_labels3 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group3/gt_and_results_e58.pkl")


# outputs1, gt_labels1 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group1_v1/gt_and_results_e5.pkl")
# outputs2, gt_labels2 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group2_v1/gt_and_results_e14.pkl")
# outputs3, gt_labels3 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group3_v1/gt_and_results_e43.pkl")


outputs = np.hstack((outputs1[:, :11], outputs2, outputs3))
gt_labels = np.hstack((gt_labels1[:, :11], gt_labels2, gt_labels3))

head_score = calculate_mAP(outputs[:, :22], gt_labels[:, :22])[0]
mid_score = calculate_mAP(outputs[:, 22:55], gt_labels[:, 22:55])[0]
tail_score = calculate_mAP(outputs[:, 55:], gt_labels[:, 55:])[0]
total_score = calculate_mAP(outputs, gt_labels)[0]

print(f"head mAP: {head_score:.4f}")
print(f"mid mAP: {mid_score:.4f}")
print(f"tail mAP: {tail_score:.4f}")
print(f"total mAP: {total_score:.4f}")
print([round(head_score, 4), round(mid_score, 4), round(tail_score, 4), round(total_score, 4)])


head mAP: 0.5772
mid mAP: 0.6504
tail mAP: 0.6218
total mAP: 0.6213
[0.5772, 0.6504, 0.6218, 0.6213]


In [3]:
# head_score = calculate_mAP(outputs[:, list(class_split["head"])], gt_labels[:, list(class_split["head"])])[0]
# mid_score = calculate_mAP(outputs[:, list(class_split["middle"])], gt_labels[:, list(class_split["middle"])])[0]
# tail_score = calculate_mAP(outputs[:, list(class_split["tail"])], gt_labels[:, list(class_split["tail"])])[0]

# outputs1, gt_labels1 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group1_l0_r5/gt_and_results_e16.pkl")
# outputs2, gt_labels2 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group2/gt_and_results_e30.pkl")
# outputs3, gt_labels3 = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group3/gt_and_results_e58.pkl")


outputs1, gt_labels1 = get_gt_pred(f"work_dirs/LT_voc_resnet101_pfc_DB_uniform_bce_35_6_group1/gt_and_results_e7.pkl")
outputs2, gt_labels2 = get_gt_pred(f"work_dirs/LT_voc_resnet101_pfc_DB_uniform_bce_35_6_group2/gt_and_results_e13.pkl")
outputs3, gt_labels3 = get_gt_pred(f"work_dirs/LT_voc_resnet101_pfc_DB_uniform_bce_35_6_group3/gt_and_results_e60.pkl")


outputs = np.hstack((outputs1[:, :], outputs2, outputs3))
gt_labels = np.hstack((gt_labels1[:, :], gt_labels2, gt_labels3))

head_score = calculate_mAP(outputs[:, :6], gt_labels[:, :6])[0]
mid_score = calculate_mAP(outputs[:, 6:12], gt_labels[:, 6:12])[0]
tail_score = calculate_mAP(outputs[:, 12:], gt_labels[:, 12:])[0]
total_score = calculate_mAP(outputs, gt_labels)[0]

print(f"head mAP: {head_score:.4f}")
print(f"mid mAP: {mid_score:.4f}")
print(f"tail mAP: {tail_score:.4f}")
print(f"total mAP: {total_score:.4f}")
print([round(head_score, 4), round(mid_score, 4), round(tail_score, 4), round(total_score, 4)])


head mAP: 0.7502
mid mAP: 0.8636
tail mAP: 0.8939
total mAP: 0.8417
[0.7502, 0.8636, 0.8939, 0.8417]


In [119]:
outputs.shape

(5000, 80)

In [9]:
class_split = mmcv.load("appendix/coco/longtail2017/class_split.pkl")

from tqdm import tqdm
best_head_e = 0
best_head_score = 0
best_mid_e = 0
best_mid_score = 0
best_tail_e = 0
best_tail_score = 0
best_total_e = 0
best_total_score = 0

for i in tqdm(range( 1, 81)):
    outputs, gt_labels = get_gt_pred(f"work_dirs/LT_coco_resnet50_pfc_DB_uniform_bce_35_6_group1_l0_r18/gt_and_results_e{i}.pkl")

    # head_score = calculate_mAP(outputs[:, list(class_split["head"])], gt_labels[:, list(class_split["head"])])[0]
    # mid_score = calculate_mAP(outputs[:, list(class_split["middle"])], gt_labels[:, list(class_split["middle"])])[0]
    # tail_score = calculate_mAP(outputs[:, list(class_split["tail"])], gt_labels[:, list(class_split["tail"])])[0]


    head_score = calculate_mAP(outputs[:, :22], gt_labels[:, :22])[0]
    mid_score = calculate_mAP(outputs[:, 11:50], gt_labels[:, 11:50])[0]
    tail_score = calculate_mAP(outputs[:, 55:], gt_labels[:, 55:])[0]
    total_score = calculate_mAP(outputs, gt_labels)[0]
    if tail_score > best_tail_score:
        best_tail_score = tail_score
        best_tail_e = i
    if head_score > best_head_score:
        best_head_score = head_score
        best_head_e = i
    if mid_score > best_mid_score:
        best_mid_score = mid_score
        best_mid_e = i
    if total_score > best_total_score:
        best_total_score = total_score
        best_total_e = i
    # print(f"head mAP: {head_score:.4f}")
    # print(f"mid mAP: {mid_score:.4f}")
    # print(f"tail mAP: {tail_score:.4f}")
    # print(f"total mAP: {total_score:.4f}")
    # print([head_score])
    print(f"{100*total_score:.2f} & {100*head_score:.2f} & {100*mid_score:.2f} & {100*tail_score:.2f}")

print(f"Best head mAP: {best_head_score:.4f} at epoch {best_head_e}")
print(f"Best mid mAP: {best_mid_score:.4f} at epoch {best_mid_e}")
print(f"Best tail mAP: {best_tail_score:.4f} at epoch {best_tail_e}")
print(f"Best total mAP: {best_total_score:.4f} at epoch {best_total_e}")

# print(f"{best_total}")

  1%|▏         | 1/80 [00:00<00:32,  2.43it/s]

6.37 & 14.60 & 5.09 & 2.28


  2%|▎         | 2/80 [00:00<00:32,  2.40it/s]

9.92 & 24.48 & 8.33 & 2.40


  4%|▍         | 3/80 [00:01<00:28,  2.73it/s]

13.45 & 31.84 & 12.49 & 2.80


  5%|▌         | 4/80 [00:01<00:25,  3.01it/s]

17.49 & 37.46 & 18.33 & 3.38


  6%|▋         | 5/80 [00:01<00:22,  3.33it/s]

21.46 & 41.16 & 23.66 & 4.52


  8%|▊         | 6/80 [00:02<00:23,  3.18it/s]

25.28 & 43.97 & 29.38 & 5.47


  9%|▉         | 7/80 [00:02<00:21,  3.38it/s]

28.44 & 45.85 & 34.33 & 6.50


 10%|█         | 8/80 [00:02<00:19,  3.61it/s]

31.56 & 47.43 & 38.42 & 8.45


 11%|█▏        | 9/80 [00:02<00:19,  3.59it/s]

34.02 & 48.89 & 41.80 & 10.13


 12%|█▎        | 10/80 [00:03<00:19,  3.61it/s]

36.32 & 49.94 & 44.65 & 12.20


 14%|█▍        | 11/80 [00:03<00:18,  3.78it/s]

38.15 & 51.04 & 46.89 & 13.64


 15%|█▌        | 12/80 [00:03<00:18,  3.69it/s]

39.69 & 51.77 & 48.71 & 15.23


 16%|█▋        | 13/80 [00:03<00:17,  3.88it/s]

41.31 & 52.46 & 49.92 & 17.63


 18%|█▊        | 14/80 [00:04<00:16,  4.02it/s]

42.77 & 53.11 & 51.08 & 20.00


 19%|█▉        | 15/80 [00:04<00:18,  3.43it/s]

43.89 & 53.39 & 51.82 & 22.06


 20%|██        | 16/80 [00:04<00:19,  3.21it/s]

45.15 & 53.94 & 52.79 & 24.01


 21%|██▏       | 17/80 [00:05<00:22,  2.82it/s]

46.21 & 54.53 & 53.67 & 25.53


 22%|██▎       | 18/80 [00:05<00:21,  2.95it/s]

47.16 & 55.04 & 54.11 & 27.48


 24%|██▍       | 19/80 [00:05<00:20,  3.03it/s]

48.10 & 55.20 & 54.44 & 29.88


 25%|██▌       | 20/80 [00:06<00:22,  2.69it/s]

49.02 & 55.55 & 55.00 & 31.81


 26%|██▋       | 21/80 [00:06<00:20,  2.81it/s]

49.60 & 55.78 & 55.31 & 32.96


 28%|██▊       | 22/80 [00:06<00:19,  3.05it/s]

50.21 & 55.98 & 56.03 & 33.62


 29%|██▉       | 23/80 [00:07<00:18,  3.06it/s]

51.16 & 56.33 & 56.31 & 36.00


 30%|███       | 24/80 [00:07<00:19,  2.83it/s]

51.83 & 56.57 & 56.78 & 37.26


 31%|███▏      | 25/80 [00:07<00:17,  3.12it/s]

52.37 & 56.51 & 57.04 & 38.77


 32%|███▎      | 26/80 [00:08<00:15,  3.43it/s]

52.20 & 56.54 & 56.92 & 38.26


 34%|███▍      | 27/80 [00:08<00:14,  3.64it/s]

53.38 & 56.76 & 57.47 & 41.08


 35%|███▌      | 28/80 [00:08<00:13,  3.76it/s]

53.75 & 57.03 & 57.67 & 41.79


 36%|███▋      | 29/80 [00:08<00:13,  3.82it/s]

54.13 & 57.02 & 58.00 & 42.35


 38%|███▊      | 30/80 [00:09<00:12,  3.90it/s]

54.52 & 56.92 & 58.14 & 43.46


 39%|███▉      | 31/80 [00:09<00:12,  3.95it/s]

54.79 & 57.06 & 58.20 & 44.24


 40%|████      | 32/80 [00:09<00:14,  3.36it/s]

54.89 & 57.29 & 58.48 & 44.12


 41%|████▏     | 33/80 [00:10<00:14,  3.31it/s]

55.57 & 57.13 & 58.63 & 46.01


 42%|████▎     | 34/80 [00:10<00:14,  3.26it/s]

55.73 & 57.28 & 58.64 & 46.50


 44%|████▍     | 35/80 [00:10<00:16,  2.81it/s]

56.06 & 57.33 & 58.84 & 47.23


 45%|████▌     | 36/80 [00:11<00:17,  2.51it/s]

56.30 & 57.34 & 58.87 & 47.84


 46%|████▋     | 37/80 [00:11<00:15,  2.77it/s]

56.43 & 57.22 & 59.05 & 48.09


 48%|████▊     | 38/80 [00:11<00:14,  2.97it/s]

56.54 & 57.25 & 59.07 & 48.44


 49%|████▉     | 39/80 [00:12<00:12,  3.20it/s]

56.96 & 57.31 & 59.18 & 49.55


 50%|█████     | 40/80 [00:12<00:11,  3.40it/s]

56.91 & 57.21 & 59.15 & 49.40


 51%|█████▏    | 41/80 [00:12<00:11,  3.47it/s]

56.91 & 57.31 & 59.24 & 49.33


 52%|█████▎    | 42/80 [00:12<00:10,  3.55it/s]

57.18 & 56.94 & 59.25 & 50.17


 54%|█████▍    | 43/80 [00:13<00:09,  3.70it/s]

57.34 & 57.24 & 59.51 & 50.30


 55%|█████▌    | 44/80 [00:13<00:09,  3.82it/s]

57.58 & 57.36 & 59.66 & 50.77


 56%|█████▋    | 45/80 [00:13<00:09,  3.85it/s]

57.52 & 57.24 & 59.63 & 50.68


 57%|█████▊    | 46/80 [00:13<00:08,  3.91it/s]

57.74 & 57.27 & 59.71 & 51.27


 59%|█████▉    | 47/80 [00:14<00:08,  3.74it/s]

57.69 & 57.22 & 59.61 & 51.29


 60%|██████    | 48/80 [00:14<00:08,  3.89it/s]

57.87 & 56.99 & 59.78 & 51.67


 61%|██████▏   | 49/80 [00:14<00:07,  4.06it/s]

57.72 & 56.59 & 59.68 & 51.58


 62%|██████▎   | 50/80 [00:14<00:07,  4.05it/s]

57.78 & 56.76 & 59.52 & 51.77


 64%|██████▍   | 51/80 [00:15<00:07,  4.02it/s]

57.89 & 56.73 & 59.71 & 51.84


 65%|██████▌   | 52/80 [00:15<00:07,  3.99it/s]

58.06 & 56.66 & 59.76 & 52.37


 66%|██████▋   | 53/80 [00:15<00:06,  3.88it/s]

58.16 & 56.68 & 59.83 & 52.61


 68%|██████▊   | 54/80 [00:15<00:06,  3.75it/s]

58.22 & 56.64 & 59.90 & 52.75


 69%|██████▉   | 55/80 [00:16<00:06,  3.66it/s]

58.13 & 56.40 & 59.69 & 52.78


 70%|███████   | 56/80 [00:16<00:06,  3.49it/s]

58.17 & 56.56 & 59.81 & 52.65


 71%|███████▏  | 57/80 [00:16<00:06,  3.63it/s]

58.09 & 56.36 & 59.67 & 52.69


 72%|███████▎  | 58/80 [00:17<00:06,  3.49it/s]

58.06 & 56.42 & 59.66 & 52.69


 74%|███████▍  | 59/80 [00:17<00:05,  3.52it/s]

58.23 & 56.44 & 59.81 & 52.99


 75%|███████▌  | 60/80 [00:17<00:06,  3.21it/s]

58.19 & 56.50 & 59.76 & 52.85


 76%|███████▋  | 61/80 [00:18<00:05,  3.31it/s]

57.98 & 56.31 & 59.63 & 52.47


 78%|███████▊  | 62/80 [00:18<00:05,  3.38it/s]

58.24 & 56.47 & 59.75 & 53.03


 79%|███████▉  | 63/80 [00:18<00:04,  3.54it/s]

58.17 & 56.49 & 59.74 & 52.81


 80%|████████  | 64/80 [00:18<00:04,  3.32it/s]

58.13 & 56.46 & 59.83 & 52.68


 81%|████████▏ | 65/80 [00:19<00:05,  2.78it/s]

58.27 & 56.64 & 59.96 & 52.80


 82%|████████▎ | 66/80 [00:20<00:09,  1.41it/s]

58.23 & 56.49 & 59.84 & 52.87


 84%|████████▍ | 67/80 [00:21<00:07,  1.70it/s]

58.33 & 56.49 & 59.86 & 53.10


 85%|████████▌ | 68/80 [00:21<00:05,  2.07it/s]

58.16 & 56.43 & 59.74 & 52.82


 86%|████████▋ | 69/80 [00:21<00:04,  2.44it/s]

58.18 & 56.30 & 59.80 & 52.85


 88%|████████▊ | 70/80 [00:21<00:03,  2.82it/s]

58.10 & 56.36 & 59.75 & 52.65


 89%|████████▉ | 71/80 [00:22<00:02,  3.15it/s]

58.26 & 56.49 & 59.77 & 53.09


 90%|█████████ | 72/80 [00:22<00:02,  3.40it/s]

58.18 & 56.33 & 59.76 & 52.89


 91%|█████████▏| 73/80 [00:22<00:01,  3.65it/s]

58.30 & 56.37 & 59.79 & 53.19


 92%|█████████▎| 74/80 [00:22<00:01,  3.89it/s]

58.20 & 56.26 & 59.82 & 52.87


 94%|█████████▍| 75/80 [00:23<00:01,  3.86it/s]

58.19 & 56.35 & 59.77 & 52.91


 95%|█████████▌| 76/80 [00:23<00:01,  3.80it/s]

58.08 & 56.33 & 59.68 & 52.70


 96%|█████████▋| 77/80 [00:23<00:00,  4.00it/s]

58.16 & 56.43 & 59.77 & 52.79


 98%|█████████▊| 78/80 [00:23<00:00,  4.11it/s]

58.33 & 56.57 & 59.96 & 53.01


 99%|█████████▉| 79/80 [00:24<00:00,  4.18it/s]

58.25 & 56.42 & 59.79 & 53.00


100%|██████████| 80/80 [00:24<00:00,  3.28it/s]

58.32 & 56.52 & 59.85 & 53.12
Best head mAP: 0.5736 at epoch 44
Best mid mAP: 0.5996 at epoch 78
Best tail mAP: 0.5319 at epoch 73
Best total mAP: 0.5833 at epoch 78
