In [3]:
import mmcv

/home/mark/Desktop/工研院/DistributionBalancedLoss/.venv/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(


In [4]:
group3 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group3/gt_and_results_e12.pkl")

In [9]:
group3[0].keys()


dict_keys(['gt_labels', 'outputs'])

In [5]:
from sklearn.metrics import average_precision_score
import numpy as np
from typing import Tuple

def calculate_mAP(all_preds: np.ndarray, all_labels: np.ndarray) -> Tuple[np.float64, list]:
    label_cnt = len(all_labels[0])
    mAP = 0
    mAP_per_label = []
    print(label_cnt)
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    for i in range(label_cnt):
        print(np.sum(all_labels[:, i]) > 0)
        AP = average_precision_score(all_labels[:, i], all_preds[:, i])
        mAP_per_label.append(AP)
        mAP += AP

    mAP /= label_cnt
    APs = average_precision_score(all_labels, all_preds, average=None) 
    mAP = APs.mean()

    return mAP, mAP_per_label



# Example: 3 samples, 3 classes (multi-label classification)
map_score = calculate_mAP( np.array(group3[0]['outputs'])[:, 1:], np.array(group3[0]['gt_labels'])[:, 1:])
print(f"mAP: {map_score[0]:.4f}")

3
True
True
True
mAP: 0.8060


In [6]:
group4 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group4/gt_and_results_e32.pkl")
group4


[{'gt_labels': [array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 1, 0], dtype=int32),
   array([1, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([1, 0, 1, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], d

In [43]:
map_score =  calculate_mAP( np.array(group4[0]['outputs'])[:, :3], np.array(group4[0]['gt_labels'])[:, :3])
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

3
True
True
True
mAP: 0.9150


array([0.89665711, 0.94408316, 0.90426001])

In [40]:
group4[0]['gt_labels'][:3]

[array([0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0], dtype=int32)]

# voc group mid

In [1]:
(0.9150+0.8060)/2

0.8605

In [7]:
map_score =  calculate_mAP( np.array(group4[0]['outputs'])[:, 3:], np.array(group4[0]['gt_labels'])[:, 3:])
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

2
True
True
mAP: 0.8775


array([0.86014269, 0.8947774 ])

In [8]:
group5 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group5/gt_and_results_e72.pkl")

In [10]:
map_score =  calculate_mAP( np.array(group5[0]['outputs']), np.array(group5[0]['gt_labels']))
print(f"mAP: {map_score[0]:.4f}")

6
True
True
True
True
True
True
mAP: 0.8768


# voc group tail

In [11]:
(0.8775*2+0.8768*6)/8

0.876975

In [12]:
group1 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group1/gt_and_results_e2.pkl")

In [13]:
group2 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group2/gt_and_results_e3.pkl")

In [14]:
map_score =  calculate_mAP( np.array(group1[0]['outputs']), np.array(group1[0]['gt_labels']))
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

2
True
True
mAP: 0.7948


array([0.92350294, 0.6659979 ])

In [15]:
map_score =  calculate_mAP( np.array(group2[0]['outputs']), np.array(group2[0]['gt_labels']))
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

3
True
True
True
mAP: 0.7695


array([0.90976081, 0.81141457, 0.58728874])

In [17]:
map_score =  calculate_mAP( np.array(group3[0]['outputs'])[:, :1], np.array(group3[0]['gt_labels'])[:, :1])
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

1
True
mAP: 0.6293


array([0.62934539])

In [18]:
(0.7948*2+0.7695*3+0.6293)/6

0.7545666666666667