In [8]:
import mmcv

In [9]:
group3 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_uniform_bce_35_6_group2/gt_and_results_e12.pkl")

In [10]:
len(group3[0]['gt_labels'])


4952

In [11]:
from sklearn.metrics import average_precision_score
import numpy as np
from typing import Tuple

def calculate_mAP(all_preds: np.ndarray, all_labels: np.ndarray) -> Tuple[np.float64, list]:
    label_cnt = len(all_labels[0])
    mAP = 0
    mAP_per_label = []
    print(label_cnt)
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    for i in range(label_cnt):
        # print(np.sum(all_labels[:, i]) > 0)
        AP = average_precision_score(all_labels[:, i], all_preds[:, i])
        mAP_per_label.append(AP)
        mAP += AP

    mAP /= label_cnt
    APs = average_precision_score(all_labels, all_preds, average=None) 
    mAP = APs.mean()

    return mAP, mAP_per_label



# Example: 3 samples, 3 classes (multi-label classification)
map_score = calculate_mAP( np.array(group3[0]['outputs'])[:, :1], np.array(group3[0]['gt_labels'])[:, :1])
print(f"mAP: {map_score[0]:.4f}")

1
mAP: 0.6145


In [6]:
group4 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group4/gt_and_results_e32.pkl")
group4


[{'gt_labels': [array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 1, 0], dtype=int32),
   array([1, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([1, 0, 1, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 0, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], dtype=int32),
   array([0, 1, 0, 0, 0], d

In [43]:
map_score =  calculate_mAP( np.array(group4[0]['outputs'])[:, :3], np.array(group4[0]['gt_labels'])[:, :3])
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

3
True
True
True
mAP: 0.9150


array([0.89665711, 0.94408316, 0.90426001])

In [40]:
group4[0]['gt_labels'][:3]

[array([0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0], dtype=int32)]

# voc group mid

In [1]:
(0.9150+0.8060)/2

0.8605

In [7]:
map_score =  calculate_mAP( np.array(group4[0]['outputs'])[:, 3:], np.array(group4[0]['gt_labels'])[:, 3:])
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

2
True
True
mAP: 0.8775


array([0.86014269, 0.8947774 ])

In [8]:
group5 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group5/gt_and_results_e72.pkl")

In [10]:
map_score =  calculate_mAP( np.array(group5[0]['outputs']), np.array(group5[0]['gt_labels']))
print(f"mAP: {map_score[0]:.4f}")

6
True
True
True
True
True
True
mAP: 0.8768


# voc group tail

In [11]:
(0.8775*2+0.8768*6)/8

0.876975

In [12]:
group1 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group1/gt_and_results_e2.pkl")

In [13]:
group2 = mmcv.load("work_dirs/LT_voc_resnet50_pfc_DB_group2/gt_and_results_e3.pkl")

In [14]:
map_score =  calculate_mAP( np.array(group1[0]['outputs']), np.array(group1[0]['gt_labels']))
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

2
True
True
mAP: 0.7948


array([0.92350294, 0.6659979 ])

In [15]:
map_score =  calculate_mAP( np.array(group2[0]['outputs']), np.array(group2[0]['gt_labels']))
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

3
True
True
True
mAP: 0.7695


array([0.90976081, 0.81141457, 0.58728874])

In [17]:
map_score =  calculate_mAP( np.array(group3[0]['outputs'])[:, :1], np.array(group3[0]['gt_labels'])[:, :1])
print(f"mAP: {map_score[0]:.4f}")

np.array(map_score[1])

1
True
mAP: 0.6293


array([0.62934539])

# voc group head

In [18]:
(0.7948*2+0.7695*3+0.6293)/6

0.7545666666666667

# check class freq

In [5]:
import mmcv

In [14]:
old_class_freq = mmcv.load("appendix/coco/longtail2017/class_freq.pkl")


In [15]:
new_class_freq = mmcv.load("/home/mark/Desktop/工研院/multi-label_classification/data/coco/DB/class_freq.pkl")

In [16]:
new_class_freq

{'gt_labels': [[1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   1,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0],
  [0,
   0,
   0,
   0,
 

In [17]:
old_class_freq

{'gt_labels': [array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
   

In [13]:
import numpy as np

def deep_equal(a, b):
    if isinstance(a, dict) and isinstance(b, dict):
        if a.keys() != b.keys():
            return False
        return all(deep_equal(a[k], b[k]) for k in a)
    elif isinstance(a, (list, np.ndarray)) and isinstance(b, (list, np.ndarray)):
        return np.array_equal(np.array(a), np.array(b))
    else:
        return a == b

deep_equal(new_class_freq, old_class_freq)

True

In [22]:
import numpy as np

def deep_diff(a, b, path=""):
    diffs = []

    if isinstance(a, dict) and isinstance(b, dict):
        a_keys, b_keys = set(a.keys()), set(b.keys())
        all_keys = a_keys.union(b_keys)
        print(all_keys)
        for key in all_keys:
            sub_path = f"{path}.{key}" if path else str(key)
            if key not in a:
                diffs.append(f"{sub_path} missing in first")
            elif key not in b:
                diffs.append(f"{sub_path} missing in second")
            else:
                diffs.extend(deep_diff(a[key], b[key], sub_path))
    elif isinstance(a, (list, np.ndarray)) and isinstance(b, (list, np.ndarray)):
        a_arr, b_arr = np.array(a), np.array(b)
        if not np.array_equal(a_arr, b_arr):
            diffs.append(f"{path} differs: {a_arr} != {b_arr}")
    else:
        if a != b:
            diffs.append(f"{path} differs: {a} != {b}")
    
    return diffs

# Usage
diffs = deep_diff(new_class_freq, old_class_freq)
if diffs:
    print("Differences found:")
    for diff in diffs:
        print("-", diff)
else:
    print("No differences.")


{'condition_prob', 'class_freq', 'gt_labels', 'neg_class_freq'}
Differences found:
- gt_labels differs: [[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] != [[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]]


In [24]:
a = np.array(new_class_freq['gt_labels'])
b = np.array(old_class_freq['gt_labels'])

def same_rows_ignore_order(a, b):
    if a.shape != b.shape:
        return False

    a_rows = np.ascontiguousarray(a).view([('', a.dtype)] * a.shape[1])
    b_rows = np.ascontiguousarray(b).view([('', b.dtype)] * b.shape[1])
    
    a_sorted = np.sort(a_rows, axis=0)
    b_sorted = np.sort(b_rows, axis=0)
    
    return np.array_equal(a_sorted, b_sorted)

same_rows_ignore_order(a, b)

True

['gt_labels differs: [[1 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]\n ...\n [1 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]] != [[1 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]\n [1 1 1 ... 0 0 0]\n ...\n [1 0 1 ... 0 0 0]\n [1 0 0 ... 0 0 0]\n [1 0 1 ... 0 0 0]]']

In [ ]:
# 1.5 0.2

In [2]:
import re
import mmcv


def get_epoch(file_path: str):
# Read the file
  with open(file_path, "r") as file:
      content = file.read()

  # Use regex to extract the number after "mAP:"
  match = re.search(r"mAP:\s*(\d+)", content)
  if match:
      epoch = int(match.group(1))
      return epoch
  else:
      print("Epoch not found.")

def get_gt_pred(file_path: str):
    output_and_gt = mmcv.load(file_path)
    return output_and_gt[0]['outputs'], output_and_gt[0]['gt_labels']

/home/mark/Desktop/工研院/DistributionBalancedLoss/.venv/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(


In [20]:
import re
import mmcv


def get_epoch(file_path: str):
# Read the file
  with open(file_path, "r") as file:
      content = file.read()

  # Use regex to extract the number after "mAP:"
  match = re.search(r"mAP:\s*(\d+)", content)
  if match:
      epoch = int(match.group(1))
      return epoch
  else:
      print("Epoch not found.")

def get_gt_pred(file_path: str):
    output_and_gt = mmcv.load(file_path)
    return output_and_gt[0]['outputs'], output_and_gt[0]['gt_labels']
import numpy as np
outputs_result = None
gt_labels_result = None
for i in range(1,3):
    # file_path = f"voc_group{i}.txt"
    # epoch = get_epoch(file_path)
    # outputs, gt_labels = get_gt_pred(f"work_dirs/LT_voc_resnet50_pfc_DB_group{i}/gt_and_results_e{epoch}.pkl")
    if i == 1:
        outputs,gt_labels = get_gt_pred("work_dirs/LT_voc_resnet50_pfc_DB_uniform_bce_35_6_group1/gt_and_results_e5.pkl")
    else:
        outputs, gt_labels = get_gt_pred(f"work_dirs/LT_voc_resnet50_pfc_DB_2_uniform_bce_35_6_group{i}/gt_and_results_e17.pkl")
    if outputs_result is None:
        outputs_result = outputs
    else:
        outputs_result = np.hstack((np.array(outputs_result), np.array(outputs)))
    if gt_labels_result is None:
        gt_labels_result = gt_labels
    else:
        gt_labels_result = np.hstack((np.array(gt_labels_result), np.array(gt_labels)))
    

In [14]:
outputs_result.shape

(4952, 20)

In [15]:
gt_labels_result.shape

(4952, 20)

In [21]:
from sklearn.metrics import average_precision_score
import numpy as np
from typing import Tuple

def calculate_mAP(all_preds: np.ndarray, all_labels: np.ndarray) -> Tuple[np.float64, list]:
    label_cnt = len(all_labels[0])
    mAP = 0
    mAP_per_label = []
    print(label_cnt)
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    for i in range(label_cnt):
        # print(np.sum(all_labels[:, i]) > 0)
        AP = average_precision_score(all_labels[:, i], all_preds[:, i])
        mAP_per_label.append(AP)
        mAP += AP

    mAP /= label_cnt
    APs = average_precision_score(all_labels, all_preds, average=None) 
    mAP = APs.mean()

    return mAP, mAP_per_label
def get_3_split_map(outputs_result, gt_labels_result):
    map_score1 =  calculate_mAP( np.array(outputs_result)[:, :6], np.array(gt_labels_result)[:, :6])
    # print(f"head mAP: {map_score1[0]:.4f}")
    # print(np.array(map_score[1]))
    map_score2 =  calculate_mAP( np.array(outputs_result)[:, 6:12], np.array(gt_labels_result)[:, 6:12])
    # print(f"mid mAP: {map_score2[0]:.4f}")
    # print(np.array(map_score[1]))
    # map_score3 =  calculate_mAP( np.array(outputs_result)[:, 12:], np.array(gt_labels_result)[:, 12:])

    # total = calculate_mAP( np.array(outputs_result), np.array(gt_labels_result))
    # print(f"tail mAP: {map_score3[0]:.4f}")
    print([round(map_score1[0], 4), round(map_score2[0], 4), ])
    # print(np.array(map_score[1]))


In [22]:
get_3_split_map(outputs_result, gt_labels_result)

6
6
[0.7557, 0.8704]


In [23]:
epoch_list = []

for i in range(1,80):
    # epoch = get_epoch(file_path)
    outputs, gt_labels = get_gt_pred(f"work_dirs/LT_voc_resnet50_pfc_DB_uniform_bce/gt_and_results_e{i}.pkl")
    epoch_list.append((outputs, gt_labels))


import numpy as np

best_head = (-1, -1)  # (score, index)
best_mid = (-1, -1)
best_tail = (-1, -1)
best_total = (-1, -1)

for idx, (outputs, gt_labels) in enumerate(epoch_list):
    outputs = np.array(outputs)
    gt_labels = np.array(gt_labels)

    head_score = calculate_mAP(outputs[:, :6], gt_labels[:, :6])[0]
    mid_score = calculate_mAP(outputs[:, 6:12], gt_labels[:, 6:12])[0]
    tail_score = calculate_mAP(outputs[:, 12:], gt_labels[:, 12:])[0]
    total_score = calculate_mAP(outputs, gt_labels)[0]

    if head_score > best_head[0]:
        best_head = (head_score, idx)
    if mid_score > best_mid[0]:
        best_mid = (mid_score, idx)
    if tail_score > best_tail[0]:
        best_tail = (tail_score, idx)
    if total_score > best_total[0]:
        best_total = (total_score, idx)

print(f"Best head mAP: {best_head[0]:.4f} at index {best_head[1]}")
print(f"Best mid mAP: {best_mid[0]:.4f} at index {best_mid[1]}")
print(f"Best tail mAP: {best_tail[0]:.4f} at index {best_tail[1]}")
print(f"Best total mAP: {best_total[0]:.4f} at index {best_total[1]}")
    

6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
6
6
8
20
Best head mAP: 0.8423 at index 71
Best mid mAP: 0.8168 at index 40
Best tail mAP: 0.8246 at index 45
Best total mAP: 0.8257 at index 73


In [24]:
outputs, gt_labels =epoch_list[73]
map_score1 =  calculate_mAP( np.array(outputs)[:, :6], np.array(gt_labels)[:, :6])
print(f"head mAP: {map_score1[0]:.4f}")
# print(np.array(map_score[1]))
map_score2 =  calculate_mAP( np.array(outputs)[:, 6:12], np.array(gt_labels)[:, 6:12])
print(f"mid mAP: {map_score2[0]:.4f}")
# print(np.array(map_score[1]))
map_score3 =  calculate_mAP( np.array(outputs)[:, 12:], np.array(gt_labels)[:, 12:])
print(f"mid mAP: {map_score3[0]:.4f}")
total = calculate_mAP( np.array(outputs), np.array(gt_labels))
    # print(f"tail mAP: {map_score3[0]:.4f}")
print([round(map_score1[0], 4), round(map_score2[0], 4), round(map_score3[0], 4), round(total[0], 4)])

6
head mAP: 0.8418
6
mid mAP: 0.8153
8
mid mAP: 0.8215
20
[0.8418, 0.8153, 0.8215, 0.8257]
